let a= 30; 
let b= 5;  
let Sum= a+b;  
let Res= a-b;  
let Multi= a*b;  
let Divi= a/b;  
let Compa1= a==b;  
let Compa2= a!=b; 
let Compa3= a>b; 
let Compa4= a<b; 
let Compa5= a>=b; 
let Compa6= a<=b;  
console.log("el resultado de la suma es: "+Sum); 
console.log("el resultado de la resta es: "+Res);  
console.log("el resultado de la multiplicacion es: "+Multi); 
console.log("el resultado de la division es: "+Divi);  
console.log("a es igual que b: "+Compa1); 
console.log("a es diferente de b: "+Compa2); 
console.log("a es mayor que b: "+Compa3); 
console.log("a es menor que b: "+Compa4); 
console.log("a es mayor o igual que b: "+Compa5); 
console.log("a es menor o igual que b: "+Compa6);

document.write("el resultado de la suma es: "+Sum); 
document.write("<br>"); 
document.write("el resultado de la resta es: "+Res); 
document.write("<br>"); 
document.write("el resultado de la multiplicacion es: "+Multi); 
document.write("<br>"); 
document.write("el resultado de la division es: "+Divi); 
document.write("<br>"); 
document.write("a es igual que b: "+Compa1); 
document.write("<br>"); 
document.write("a es diferente de b: "+Compa2); 
document.write("<br>"); 
document.write("a es mayor que b: "+Compa3); 
document.write("<br>");
document.write("a es menor que b: "+Compa4); 
document.write("<br>");
document.write("a es mayor o igual que b: "+Compa5); 
document.write("<br>");
document.write("a es menor o igual que b: "+Compa6); 
document.write("<br>");
